# Generated by Django 5.0.1 on 2024-11-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podproduct',
            name='created_by',
        ),
        migrations.AddField(
            model_name='customizedproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customizedproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='podproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='podproduct',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
